# This is all an external repo needs to include in ./github/workflows
name: Beta release

on:
  pull_request:
    types:
      # Label is added to the PR
      - labeled
      # A push is made to the PR
      - synchronize

jobs:
  beta-release:
    uses: krogertechnology/kat-web-katomatic/.github/workflows/beta-release.yml@main
    secrets:
      token: ${{ secrets.WORKFLOW_PAT }}
