name: CODEOWNERS lint

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  code-owners-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: mszostok/codeowners-validator@v0.6.0
        with:
          checks: "files,owners,duppatterns,syntax"
          # GitHub access token is required only if the `owners` check is enabled
          experimental_checks: "notowned"
          github_access_token: ${{ secrets.ACCESS_TOKEN }}
