name: Test ENV. vars

on:
#   push:
#     paths:
#       - '.github/workflows/test.envs.yml'
      
  workflow_dispatch:
    inputs:
      sdk:
        type: choice
        options: #No support yet to have dynamic inputs, say types from a json file.
          - sdk1
          - sdk2
          - lodash
        description: "Library to bump"
        required: true
        default: "lodash"
      version: #Do we not bump to the latest always? If so, we wont really need this.
        description: "Release Version" 
        required: true
        default: "4.17.21"

env:
  sdk1: sdk1
  sdk2: sdk2
  lodash: lodash  
  inputSdk: ${{ github.event.inputs.sdk }}
  
  
jobs:
  
  map-env:
    runs-on: ubuntu-latest
    steps:
      - name: check input to env
        run: |
          echo ${{ github.event.inputs.sdk }}
          echo ${{ env.lodash }}
          echo "INPUTT=${{ env.lodash }}" >> $GITHUB_ENV
          echo $INPUTT
          
      - name: IF Input, then output
        run: |
          if [ env.inputSdk == env.sdk1]
          then
            echo "outputting sdk1"
          else
            echo "Not sdk1"
          fi
          
# echo ${{ env.$INPUTT }} #not valid.

