name: Demonstration
on:
  workflow_dispatch:
  
jobs:
  first-job:
    runs-on: ubuntu-latest  
    
    steps:
    - uses: actions/checkout@v2
    - id: identify
      run: |
        # use bash variable expression to get the substring
        export GIT_PR_SHA="${{ github.sha }}"
        export GIT_PR_SHA_SHORT="${GIT_PR_SHA:0:10}"

        echo "::set-output name=git_pr_sha::${GIT_PR_SHA}"
        echo "::set-output name=git_pr_sha_short::${GIT_PR_SHA_SHORT}"

    - id: get_consumers
      uses: notiz-dev/github-action-json-property@release
      with: 
          path: 'consumers.json'
          prop_path: 'sdk1'
    - run: |
        export CONSUMERS="${steps.get_consumers.outputs.prop}"
        echo "::set-output name=consumers::${CONSUMERS}"
#     export GIT_PR_SHA_SHORT="${GIT_PR_SHA:0:10}"
#     echo "::set-output name=git_pr_sha::${GIT_PR_SHA}"
 
    outputs:
      git_pr_sha: ${{ steps.identify.outputs.git_pr_sha }}
      git_pr_sha_short: ${{ steps.identify.outputs.git_pr_sha_short }}
      consumers: ${{ steps.get_consumers.outputs.consumers }}
    
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "${{ needs.first-job.outputs.git_pr_sha }}"
        echo "${{ needs.first-job.outputs.git_pr_sha_short }}"
        echo "${{ needs.first-job.outputs.consumers }}"
