name: Test Exports
on:
  push:
    paths:
      - '.github/workflows/test-exports.yml'
  
jobs:
  first-job:
    runs-on: ubuntu-latest  
    
    steps:
    - uses: actions/checkout@v2
    - id: identify
      run: |
        # use bash variable expression to get the substring
        export GIT_PR_SHA="${{ github.sha }}"
        export GIT_PR_SHA_SHORT="${GIT_PR_SHA:0:10}"

        echo "::set-output name=git_pr_sha::${GIT_PR_SHA}"
        echo "::set-output name=git_pr_sha_short::${GIT_PR_SHA_SHORT}"

    - id: get_consumers
      uses: notiz-dev/github-action-json-property@release
      with: 
          path: 'consumers.json'
          prop_path: 'lodash'
    - run: |
        export CONSUMERS="${{steps.get_consumers.outputs.prop}}"
        echo "notiz export: ${CONSUMERS}"
        echo "::set-output name=consumers::${CONSUMERS}"
        
    - id: jq_consumers
      run: |
        export jqcs=$(jq '.lodash' <<< $(cat ./consumers.json))
        echo "jq export: ${jqcs}"
        echo "::set-output name=jqConsumers::${jqcs}"
 
    outputs:
      git_pr_sha: ${{ steps.identify.outputs.git_pr_sha }}
      git_pr_sha_short: ${{ steps.identify.outputs.git_pr_sha_short }}
      consumersNoitzDev: ${{ steps.get_consumers.outputs.consumers }}
      jqConsumers: ${{ steps.jq_consumers.outputs.jqConsumers }}
    
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo "fromJson notiz export: ${{ fromJson(needs.first-job.outputs.consumersNoitzDev) }}"
        echo "fromJson jq export: ${{ fromJson(needs.first-job.outputs.jqConsumers) }}"
#     echo "${{ needs.first-job.outputs.git_pr_sha }}"
#     echo "${{ needs.first-job.outputs.git_pr_sha_short }}"
#     echo "jq export: ${{ needs.first-job.outputs.jqConsumers }}"
#     echo "notiz export: ${{ needs.first-job.outputs.consumersNoitzDev }}"
