name: Test Checkout and PR

on:
  workflow_dispatch:
  
jobs:
  bump-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set Global Data
        id: global_data
        run: |
          echo "::set-output name=date::$(date +'%Y-%m-%d')"
         
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.TOKEN }}
          repository: git@github.com:sujanp-kr/consumer-A.git
          path: clonedRepo

      - name: Update SDK version
        run: |
          pwd
          ls -la
          cd clonedRepo
          ls -la
          cat > test.txt
          ls -la

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.TOKEN }}
          path: clonedRepo
          commit-message: "[Auto] Check new file creation"
          committer: Katomatic <noreply@kroger.com>
          author: automation <automation@user.noreply.kroger.com>
          signoff: false
#           base: main
          # base: ${{ steps.global_data.outputs.defaultBranch }}
          branch: automation/checkout-and-pr-${{steps.global_data.outputs.date}}
          delete-branch: true
          title: "[KAT][Automation] Bump ${{github.event.inputs.sdk}} to ${{github.event.inputs.version}}"
          body: |
            Bump sdk version
            - Updated ${{ steps.global_data.outputs.date }}
            - Auto-generated by Katomatic
          labels: version-patch
          assignees: sujanp-kr
          team-reviewers: |
            owners
            maintainers
          draft: false
