name: Version Bump at Consumers

on:
  #Could automate this further by a making it a workflow_call, summoned from any SDK once it has a new tag; or another cron job on a schedule.
  workflow_dispatch:
    inputs:
      sdk:
        type: choice
        options:
          - sdk1
          - sdk2
        description: "Library to bump"
        required: true
        default: "sdk1"
      version:
        description: "Release Version"
        required: true
        default: "11.11.11"

# Avoiding this for now since no multi-select in github workflow yet; 
# Also to reduce complexity to change consumer list based on sdk choice above
#       consumer:
#         type: choice 
#         options: 
#           - Consumer-A
#           - All 
#         description: "Environment to Deploy to"
#         required: true


jobs:

  get_consumers_for_sdk:
    runs-on: ubuntu-latest
    
    outputs:
      consumers: ${{steps.get-consumers.outputs.consumers}}

    steps:
      - uses: actions/checkout@v2
      
#       - name: Setup Node
#         uses: actions/setup-node@v2
#         with:
#           node-version: 14.17.6
          
#       - name: Install Yarn
#         run: npm indtall -g yarn
        
#       - name: Install Depndencies
#         run: yarn
        
      - name: Get Consumers for Input SDK
        id: get-consumers
        run: echo "::set-output name=consumers::[\"consumer-A\", \"consumer-B\"]"

  bump-consumer:
    runs-on: ubuntu-latest
    needs: get_consumers_for_sdk
    strategy:
      fail-fast: false
      matrix:
        target: [consumer-A, consumer-B]
    steps:
      - name: Check inputs
        run: |
          echo ${{ github.event.inputs.sdk }}
          echo ${{ github.event.inputs.version }}
          echo "Got matrix: ${{needs.get_consumers_for_sdk.outputs.consumers}}"
          echo "Working with ${{ matrix.target }}"
          
